#!/usr/bin/env python

import matplotlib.pyplot as plt
import foale.mnsa
import numpy as np
from pydl.pydlutils import sdss

# Initialize the convenience object; below are the plate IFUs of the 6 galaxies we are interested in from Belfiore 2016
#10001-12701, 7975-9101, 7977-12704, 8439-12702, 7975-3704, 7443-12703, 8143-6101

p_IFU = '7977-12704'

m = foale.mnsa.MNSA(plateifu = '7977-12704')

# Read in the cube's FITS file
m.read_cube()
wave = m.cube['WAVE'].read()
flux = m.cube['FLUX'].read()

# Show one of the spectra in a pixel
spaxel_flux = flux[:, 24, 24]
#plt.plot(wave, spaxel_flux)
#plt.xlabel('Wavelength (Angstrom)')
#plt.ylabel('Flux ($10^{-17}$ erg/cm$^2$/s/A)')
#plt.title(p_IFU)
#plt.show()

# Read in the maps FITS file
m.read_maps()

# Read in the emission line measurements (Gaussian fit)
# This is a big 3D array, with one 2D image per line.
gflux = m.maps['EMLINE_GFLUX'].read()

# We have to pick out the right line. The MNSA object
# builds a little dictionary to help.
#print(m.lineindx.keys())

halpha_indx = m.lineindx['Ha-6564']
hbeta_indx = m.lineindx['Hb-4862']
SII_indx = m.lineindx['SII-6718']
OI_indx = m.lineindx['OI-6302']
OIII_indx = m.lineindx['OIII-5008']
NII_indx = m.lineindx['NII-6585']

#DAP Maps for Emission Lines of Interest
halpha = gflux[halpha_indx, :, :]
plt.imshow(halpha, origin='lower', cmap='inferno')
plt.title('H-Alpha')
plt.colorbar(label = 'Flux')
plt.show()

hbeta = gflux[halpha_indx, :, :]
#plt.imshow(hbeta, origin='lower', cmap='Greys')
#plt.title('H-Beta')
#plt.show()

SII = gflux[SII_indx, :, :]
#plt.imshow(SII, origin='lower', cmap='Greys')
#plt.title('SII')
#plt.colorbar(label = 'Flux')
#plt.show()

#OI = gflux[OI_indx, :, :]
#plt.imshow(OI, origin='lower', cmap='Greys')
#plt.title('OI')
#plt.colorbar(label = 'Flux')
#plt.show()

OIII = gflux[OIII_indx, :, :]
#plt.imshow(OIII, origin='lower', cmap='Greys')
#plt.title('OIII')
#plt.colorbar(label = 'Flux')
#plt.show()

#NII = gflux[NII_indx, :, :]
#plt.imshow(NII, origin='lower', cmap='Greys')
#plt.title('NII')
#plt.colorbar(label = 'Flux')
#plt.show()

#attempting to plot a masked h-alpha DAP map
gfluxmask = m.maps['EMLINE_GFLUX_MASK'].read()
halpha_mask = np.ma.array(halpha, mask = gfluxmask[halpha_indx,:,:])
plt.imshow(halpha_mask, origin = 'lower', cmap = 'inferno')
plt.title('Masked H-Alpha')
plt.colorbar()
plt.show()

#if above is correct, then these are the masked arrays for all other emission lines of interest:
hbeta_mask = np.ma.array(hbeta, mask = gfluxmask[hbeta_indx,:,:])
SII_mask = np.ma.array(SII, mask = gfluxmask[SII_indx,:,:])
OIII_mask = np.ma.array(OIII, mask fluxmask[OIII_indx,:,:])

#don't want divide by zero errors when we calculate line ratios; make a mask to pick out good values that don't equal 0: 
m = (halpha_mask != 0) | (hbeta_mask != 0 ) | (SII_mask != 0) | (OIII_mask != 0) | (halpha <= 0) | (hbeta <= 0) | (SII <= 0 ) | (OIII <= 0)

#apply mask to h-alpha line emission flux measurement array
halpha_test = np.ma.array(halpha, mask = m)

plt.imshow(halpha_test, origin = 'lower', cmap = 'inferno')
plt.title('Masked H-Alpha > 0')
plt.colorbar()
plt.show()

#if above is correct then these are the correctly masked line emission flux measurements that are > 0:
hbeta_test = np.ma.array(hbeta, mask = m)
plt.imshow(hbeta_test, origin = 'lower', cmap = 'inferno')
plt.title('Masked H-Beta > 0')
plt.colorbar()
plt.show()
SII_test = np.ma.array(SII, mask = m)
plt.imshow(SII_test, origin = 'lower', cmap = 'inferno')
plt.title('Masked SII > 0')
plt.colorbar()
plt.show()
OIII_test = np.ma.array(OIII, mask = m)
plt.imshow(OIII_test, origin = 'lower', cmap = 'inferno')
plt.title('Masked OIII > 0')
plt.colorbar()
plt.show()

#BPT Diagram
#empty = []
#line_ratio1 = np.asarray(empty)
#line_ratio2 = np.asarray(empty)

#line_ratio1[good_halpha] = np.log(SII_mask[good_halpha]/
#line_ratio2[good] = np.log(OIII[good]/hbeta[good])

#plt.plot(line_ratio1, line_ratio2)
#plt.title('BPT Diagram for Galaxy', p_IFU)
#plt.show()
